baseURL: https://fletcher.gornick.dev/
languageCode: en-us
title: home
theme: PaperMod

params:
  defaultTheme: auto
  disableThemeToggle: false
  title: fletcher gornick
  description: static site for fletcher gornick
  author: Fletcher Gornick

  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true

  assets:
    favicon: /icon/favicon.ico
    favicon16x16: /icon/favicon-16x16.png
    favicon32x32: /icon/favicon-32x32.png
    apple_touch_icon: /icon/apple-icon.png

  profileMode:
    enabled: true
    title: Fletcher Gornick
    subtitle: |
      a place for me to post my stuff
    imageUrl: /profile.png
    imageTitle: profile
    imageWidth: 200
    imageHeight: 200

    buttons:
      - name: archives
        url: /archives
      - name: résumé
        url: /resume

  socialIcons:
    - name: github
      url: https://github.com/fmgornick
    - name: email
      url: mailto:fletcher@gornick.dev
    - name: linkedin
      url: https://linkedin.com/in/fletcher-gornick

menu:
  main:
    - identifier: search
      name: search
      url: /search
      weight: 10
    - identifier: projects
      name: projects
      url: /projects
      weight: 20
    - identifier: about
      name: about
      url: /about
      weight: 30
    - identifier: tags
      name: tags
      url: /tags
      weight: 40

outputs:
  home: [HTML, RSS, JSON]
