baseURL = "https://fletcher.gornick.dev/"
languageCode = "en-us"
title = "home"
theme = [ "PaperMod", "hugo-embed-pdf-shortcode" ]
enableInlineShortcodes = true

[params]
defaultTheme = "auto"
disableThemeToggle = false
title = "fletcher gornick"
description = "static site for fletcher gornick"
author = "Fletcher Gornick"
ShowRssButtonInSectionTermList = true
ShowFullTextinRSS = true

[params.assets]
favicon = "/icon/favicon.ico"
favicon16x16 = "/icon/favicon-16x16.png"
favicon32x32 = "/icon/favicon-32x32.png"
apple_touch_icon = "/icon/apple-icon.png"

[params.profileMode]
enabled = true
title = "Fletcher Gornick"
subtitle = "a place for me to post my stuff"
imageUrl = "/profile.png"
imageTitle = "profile"
imageWidth = 200
imageHeight = 200

[[params.profileMode.buttons]]
name = "archives"
url = "/archives"

[[params.profileMode.buttons]]
name = "résumé"
url = "/resume"

[[params.socialIcons]]
name = "github"
url = "https://github.com/fmgornick"

[[params.socialIcons]]
name = "email"
url = "mailto:fletcher@gornick.dev"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/fletcher-gornick"

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags"
weight = 30

[[menu.main]]
identifier = "search"
name = "search"
url = "/search"
weight = 40

[outputs]
home = [ "HTML", "RSS", "JSON" ]
