baseURL: https://fletcher.gornick.dev/
languageCode: en-us
title: fletcher
theme: PaperMod

params:
  defaultTheme: auto
  disableThemeToggle: false
  title: fletcher gornick
  description: static site for fletcher gornick
  author: Fletcher Gornick

  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true

  assets:
    favicon: /icon/favicon.ico
    favicon16x16: /icon/favicon-16x16.png
    favicon32x32: /icon/favicon-32x32.png
    apple_touch_icon:  /icon/apple-touch-icon.png

  profileMode:
    enabled: true
    title: fletcher gornick's homepage
    subtitle: |
      i’m a computer science undergrad at UMNTC 
      with a particular interest in algorithm design.
    imageUrl: /profile.png
    imageTitle: profile
    imageWidth: 200
    imageHeight: 200

    buttons:
      - name: archives
        url: /archives
      - name: resumé
        url: /resume

  socialIcons:
    - name: github
      url: https://github.com/fmgornick
    - name: email
      url: mailto:fletchermgornick@gmail.com
    - name: linkedin
      url: https://linkedin.com/in/fletcher-gornick

menu:
  main:
    - identifier: search
      name: search
      url: /search
      weight: 10
    - identifier: projects
      name: projects
      url: /projects
      weight: 20
    - identifier: contact
      name: contact
      url: /contact
      weight: 30
    - identifier: tags
      name: tags
      url: /tags
      weight: 40

outputs:
  home: [ HTML, RSS, JSON ]
